## REGISTER USER
POST http://localhost:3000/register
content-type: application/json

{
    "username": "testuser018",
    "email": "testuser018@gmail.com",
    "password": "testuser001pwd",
    "firstName": "Dimtrii",
    "lastName": "Shevelev"
}