## REGISTER USER
POST http://localhost:3000/register
content-type: application/json

{
    "username": "testuser017",
    "email": "testuser017@gmail.com",
    "password": "testuser001pwd",
    "firstName": "Dimtrii",
    "lastName": "Shevelev"
}